/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.TaiKhoanControolleerr;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.jar.Manifest;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import model.ChuyenManHinh;
import model.DanhMucBean;
import model.NhanVien;

/**
 *
 * @author trinh thanh
 */
public class Main extends javax.swing.JFrame {
    /**
     * Creates new form Main
     */
    public Main() {

        initComponents();
         this.setLocationRelativeTo(null);
        initView();

    }

    private void initView() {
        setTitle("Quản Lý Bán Sách");
        this.setLocationRelativeTo(null);

        List<DanhMucBean> arr = new ArrayList<>();
        arr.add(new DanhMucBean("TrangChu", jpntrangchu, jlbtrangchu));
        arr.add(new DanhMucBean("QuanLyNhanVien", jpnnhanvien, jlbnhanvien));
        arr.add(new DanhMucBean("QuanLyKhachHang", jpnquanlykhachhang, jlbquanlykhachhang));
        arr.add(new DanhMucBean("GiamGia", jpngiamgia, jlbgiamgia));
        arr.add(new DanhMucBean("QuanLyHoaDon", jpnhoadon, jlbhoadon));
        arr.add(new DanhMucBean("QuanLyThongKe", jpnthongke, jlbthongke));

        ChuyenManHinh chuyenManHinh = new ChuyenManHinh(jpnview);
        chuyenManHinh.setView(jpntrangchu, jlbtrangchu);
        chuyenManHinh.setEvent(arr);
        if (TaiKhoanControolleerr.quyenNhanVien.equalsIgnoreCase("Nhân Viên")) {
             jlbthongke.setVisible(false);
              jlbnhanvien.setVisible(false);
               jlbgiamgia.setVisible(false);
        }
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jpnmenu = new javax.swing.JPanel();
        jpntrangchu = new javax.swing.JPanel();
        jlbtrangchu = new javax.swing.JLabel();
        jpnnhanvien = new javax.swing.JPanel();
        jlbnhanvien = new javax.swing.JLabel();
        jpnquanlykhachhang = new javax.swing.JPanel();
        jlbquanlykhachhang = new javax.swing.JLabel();
        jpnhoadon = new javax.swing.JPanel();
        jlbhoadon = new javax.swing.JLabel();
        jpngiamgia = new javax.swing.JPanel();
        jlbgiamgia = new javax.swing.JLabel();
        jpnquanlysach1 = new javax.swing.JPanel();
        jlbquanlysach1 = new javax.swing.JLabel();
        jpnthongke = new javax.swing.JPanel();
        jlbthongke = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlbten = new javax.swing.JLabel();
        jpnview = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnRoot.setMinimumSize(new java.awt.Dimension(500, 0));
        jpnRoot.setPreferredSize(new java.awt.Dimension(1200, 1000));

        jpnmenu.setBackground(new java.awt.Color(102, 102, 153));
        jpnmenu.setForeground(new java.awt.Color(204, 204, 255));
        jpnmenu.setToolTipText("");
        jpnmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpnmenu.setMinimumSize(new java.awt.Dimension(100, 100));

        jpntrangchu.setBackground(new java.awt.Color(102, 102, 102));
        jpntrangchu.setForeground(new java.awt.Color(51, 51, 51));
        jpntrangchu.setFocusCycleRoot(true);

        jlbtrangchu.setBackground(new java.awt.Color(0, 0, 0));
        jlbtrangchu.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbtrangchu.setForeground(new java.awt.Color(255, 255, 255));
        jlbtrangchu.setText("Bán Hàng");

        javax.swing.GroupLayout jpntrangchuLayout = new javax.swing.GroupLayout(jpntrangchu);
        jpntrangchu.setLayout(jpntrangchuLayout);
        jpntrangchuLayout.setHorizontalGroup(
            jpntrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpntrangchuLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jlbtrangchu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpntrangchuLayout.setVerticalGroup(
            jpntrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbtrangchu, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jpnnhanvien.setBackground(new java.awt.Color(102, 102, 102));
        jpnnhanvien.setForeground(new java.awt.Color(0, 255, 255));

        jlbnhanvien.setBackground(new java.awt.Color(0, 0, 0));
        jlbnhanvien.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbnhanvien.setForeground(new java.awt.Color(255, 255, 255));
        jlbnhanvien.setText(" Nhân Viên");

        javax.swing.GroupLayout jpnnhanvienLayout = new javax.swing.GroupLayout(jpnnhanvien);
        jpnnhanvien.setLayout(jpnnhanvienLayout);
        jpnnhanvienLayout.setHorizontalGroup(
            jpnnhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnnhanvienLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jlbnhanvien)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnnhanvienLayout.setVerticalGroup(
            jpnnhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbnhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jpnquanlykhachhang.setBackground(new java.awt.Color(102, 102, 102));
        jpnquanlykhachhang.setForeground(new java.awt.Color(0, 255, 255));

        jlbquanlykhachhang.setBackground(new java.awt.Color(0, 0, 0));
        jlbquanlykhachhang.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbquanlykhachhang.setForeground(new java.awt.Color(255, 255, 255));
        jlbquanlykhachhang.setText("Khách Hàng");

        javax.swing.GroupLayout jpnquanlykhachhangLayout = new javax.swing.GroupLayout(jpnquanlykhachhang);
        jpnquanlykhachhang.setLayout(jpnquanlykhachhangLayout);
        jpnquanlykhachhangLayout.setHorizontalGroup(
            jpnquanlykhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnquanlykhachhangLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jlbquanlykhachhang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnquanlykhachhangLayout.setVerticalGroup(
            jpnquanlykhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbquanlykhachhang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jpnhoadon.setBackground(new java.awt.Color(102, 102, 102));
        jpnhoadon.setForeground(new java.awt.Color(0, 255, 255));

        jlbhoadon.setBackground(new java.awt.Color(0, 0, 0));
        jlbhoadon.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbhoadon.setForeground(new java.awt.Color(255, 255, 255));
        jlbhoadon.setText("Hóa Đơn");

        javax.swing.GroupLayout jpnhoadonLayout = new javax.swing.GroupLayout(jpnhoadon);
        jpnhoadon.setLayout(jpnhoadonLayout);
        jpnhoadonLayout.setHorizontalGroup(
            jpnhoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnhoadonLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jlbhoadon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnhoadonLayout.setVerticalGroup(
            jpnhoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbhoadon, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jpngiamgia.setBackground(new java.awt.Color(102, 102, 102));
        jpngiamgia.setForeground(new java.awt.Color(0, 255, 255));

        jlbgiamgia.setBackground(new java.awt.Color(0, 0, 0));
        jlbgiamgia.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbgiamgia.setForeground(new java.awt.Color(255, 255, 255));
        jlbgiamgia.setText("Giảm Giá");

        javax.swing.GroupLayout jpngiamgiaLayout = new javax.swing.GroupLayout(jpngiamgia);
        jpngiamgia.setLayout(jpngiamgiaLayout);
        jpngiamgiaLayout.setHorizontalGroup(
            jpngiamgiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpngiamgiaLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jlbgiamgia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpngiamgiaLayout.setVerticalGroup(
            jpngiamgiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbgiamgia, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        jpnquanlysach1.setBackground(new java.awt.Color(102, 102, 102));
        jpnquanlysach1.setForeground(new java.awt.Color(0, 255, 255));
        jpnquanlysach1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnquanlysach1MouseClicked(evt);
            }
        });

        jlbquanlysach1.setBackground(new java.awt.Color(0, 0, 0));
        jlbquanlysach1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbquanlysach1.setForeground(new java.awt.Color(255, 255, 255));
        jlbquanlysach1.setText("Quản Lý Sách");

        javax.swing.GroupLayout jpnquanlysach1Layout = new javax.swing.GroupLayout(jpnquanlysach1);
        jpnquanlysach1.setLayout(jpnquanlysach1Layout);
        jpnquanlysach1Layout.setHorizontalGroup(
            jpnquanlysach1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnquanlysach1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jlbquanlysach1)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jpnquanlysach1Layout.setVerticalGroup(
            jpnquanlysach1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnquanlysach1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbquanlysach1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        jpnthongke.setBackground(new java.awt.Color(102, 102, 102));
        jpnthongke.setForeground(new java.awt.Color(0, 255, 255));

        jlbthongke.setBackground(new java.awt.Color(0, 0, 0));
        jlbthongke.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbthongke.setForeground(new java.awt.Color(255, 255, 255));
        jlbthongke.setText("Thống Kê");

        javax.swing.GroupLayout jpnthongkeLayout = new javax.swing.GroupLayout(jpnthongke);
        jpnthongke.setLayout(jpnthongkeLayout);
        jpnthongkeLayout.setHorizontalGroup(
            jpnthongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnthongkeLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jlbthongke)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnthongkeLayout.setVerticalGroup(
            jpnthongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbthongke, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/tải xuống (12).png"))); // NOI18N
        jLabel1.setText("Bookbuy");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jlbten.setText("     ");

        javax.swing.GroupLayout jpnmenuLayout = new javax.swing.GroupLayout(jpnmenu);
        jpnmenu.setLayout(jpnmenuLayout);
        jpnmenuLayout.setHorizontalGroup(
            jpnmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpntrangchu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnnhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnquanlykhachhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnhoadon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpngiamgia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnquanlysach1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnthongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpnmenuLayout.createSequentialGroup()
                        .addComponent(jlbten, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jpnmenuLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnmenuLayout.setVerticalGroup(
            jpnmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbten)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jpntrangchu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnquanlykhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnquanlysach1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpngiamgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnthongke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );

        jpnview.setPreferredSize(new java.awt.Dimension(0, 1200));

        javax.swing.GroupLayout jpnviewLayout = new javax.swing.GroupLayout(jpnview);
        jpnview.setLayout(jpnviewLayout);
        jpnviewLayout.setHorizontalGroup(
            jpnviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1176, Short.MAX_VALUE)
        );
        jpnviewLayout.setVerticalGroup(
            jpnviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addComponent(jpnmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnview, javax.swing.GroupLayout.DEFAULT_SIZE, 1176, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnview, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, 1431, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1457, 718));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jpnquanlysach1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnquanlysach1MouseClicked

   

openQuanLySachWindow();
    }//GEN-LAST:event_jpnquanlysach1MouseClicked

    private void openQuanLySachWindow() {
        JFrame quanLySachFrame = new JFrame("Quản Lý Sách");
        quanLySachFrame.setSize(600, 400);
        quanLySachFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        quanLySachFrame.setLocationRelativeTo(null); // Center the new window

        // Add QuanLySachPanel to the new JFrame
        QuanThanhCon quanLySachPanel = new QuanThanhCon();
        quanLySachFrame.add(quanLySachPanel);
        quanLySachFrame.pack();
        quanLySachFrame.setVisible(true);
        this.setLocationRelativeTo(null);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlbgiamgia;
    private javax.swing.JLabel jlbhoadon;
    private javax.swing.JLabel jlbnhanvien;
    private javax.swing.JLabel jlbquanlykhachhang;
    private javax.swing.JLabel jlbquanlysach1;
    private javax.swing.JLabel jlbten;
    private javax.swing.JLabel jlbthongke;
    private javax.swing.JLabel jlbtrangchu;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpngiamgia;
    private javax.swing.JPanel jpnhoadon;
    private javax.swing.JPanel jpnmenu;
    private javax.swing.JPanel jpnnhanvien;
    private javax.swing.JPanel jpnquanlykhachhang;
    private javax.swing.JPanel jpnquanlysach1;
    private javax.swing.JPanel jpnthongke;
    private javax.swing.JPanel jpntrangchu;
    private javax.swing.JPanel jpnview;
    // End of variables declaration//GEN-END:variables
 public void createQuanThanhConPanel() {
        // Tạo JPanel mới
        QuanThanhCon newPanel = new QuanThanhCon();
        newPanel.setBackground(Color.LIGHT_GRAY);
        newPanel.add(new JLabel("Đây là trang QuanThanhCon"));

        // Xóa nội dung hiện tại của jpnview và thêm newPanel
        jpnview.removeAll();
        jpnview.add(newPanel);
        jpnview.revalidate();
        jpnview.repaint();
    }

}
