/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.TaiKhoanControolleerr;
import javax.swing.JOptionPane;
import model.LuuThongTinDangNhapSingleton;
import model.luuThongTinDangNhap;

/**
 *
 * @author trinh thanh
 */
public class DangNhap extends javax.swing.JFrame {

    private TaiKhoanControolleerr nv = new TaiKhoanControolleerr();
    luuThongTinDangNhap luDangNhap = new luuThongTinDangNhap();

    /**
     * Creates new form DangNhap1
     */
    public DangNhap() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnroot = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txttendangnhap = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passmatkhau = new javax.swing.JPasswordField();
        btnsubmit = new javax.swing.JButton();
        jlbMsg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnroot.setBackground(new java.awt.Color(51, 204, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tên Đăng Nhâp:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mật Khẩu:");

        btnsubmit.setBackground(new java.awt.Color(153, 153, 153));
        btnsubmit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsubmit.setText("ĐĂNG NHẬP");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        jlbMsg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlbMsg.setForeground(new java.awt.Color(255, 51, 51));
        jlbMsg.setText("Vui Lòng Nhập Thông Tin Đăng Nhập!");

        javax.swing.GroupLayout jpnrootLayout = new javax.swing.GroupLayout(jpnroot);
        jpnroot.setLayout(jpnrootLayout);
        jpnrootLayout.setHorizontalGroup(
            jpnrootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnrootLayout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addGroup(jpnrootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(btnsubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passmatkhau)
                    .addComponent(txttendangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );
        jpnrootLayout.setVerticalGroup(
            jpnrootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnrootLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txttendangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(passmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jlbMsg)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/istockphoto-2157176278-1024x1024_2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jpnroot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jpnroot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1035, 404));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        String taiKhoan = txttendangnhap.getText();
        String matKhau = passmatkhau.getText();

        // Kiểm tra đăng nhập
        if (nv.dangNhap(taiKhoan, matKhau)) {
            // Lấy quyền và thông tin nhân viên từ database
            String vaiTro = nv.layVaiTro(taiKhoan);  // Trả về quyền từ bảng NhanVien
            String tenNhanVien = nv.layTenNhanVien(taiKhoan); // Lấy tên nhân viên

            // Lưu thông tin đăng nhập
            luuThongTinDangNhap luDangNhap = new luuThongTinDangNhap();
            luDangNhap.setTenTaiKhoan(taiKhoan);
            luDangNhap.setQuyen(vaiTro);
            luDangNhap.setMaNV(tenNhanVien);

            // Lưu thông tin vào Singleton
            LuuThongTinDangNhapSingleton.getInstance().setThongTinDangNhap(luDangNhap);

            // Kiểm tra quyền của nhân viên
            if (nv.kiemTraQuyen(vaiTro, "Admin")) {
                JOptionPane.showMessageDialog(rootPane, "Đăng nhập thành công với quyền Admin" + tenNhanVien);
                Main mn = new Main();
                mn.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Đăng nhập thành công nhưng không có quyền Admin");
                Main mn = new Main();
                mn.setVisible(true);
                dispose();  // Đóng cửa sổ đăng nhập
            }
        } else {
            JOptionPane.showMessageDialog(this, "Tên tài khoản hoặc mật khẩu sai");
        }
       

        // Kiểm tra thông tin đăng nhập
//        TaiKhoanControolleerr nv = new TaiKhoanControolleerr();
//        if (nv.dangNhap(taiKhoan, matKhau)) {
//            // Lấy thông tin nhân viên sau khi đăng nhập thành công
//            String vaiTro = nv.layVaiTro(taiKhoan); // Quyền của nhân viên
//            String maNV = nv.layIDNhaanVien(taiKhoan); // Họ tên nhân viên
//
//            // Tạo đối tượng lưu thông tin đăng nhập
//            luuThongTinDangNhap luDangNhap = new luuThongTinDangNhap();
//            luDangNhap.setTenTaiKhoan(taiKhoan);
//            luDangNhap.setQuyen(vaiTro);
//            luDangNhap.setMaNV(maNV);
//
//            // Lưu thông tin vào Singleton
//            LuuThongTinDangNhapSingleton.getInstance().setThongTinDangNhap(luDangNhap);
//
//            // Hiển thị thông báo thành công và chuyển sang giao diện chính
////            JOptionPane.showMessageDialog(this, "Đăng nhập thành công! Chào " + maNV);
//
//            // Kiểm tra quyền truy cập
//            Main mn = new Main();
//            if (nv.kiemTraQuyen(vaiTro, "Admin")) {
//                JOptionPane.showMessageDialog(this, "Bạn đang đăng nhập với quyền Admin.");
//            } else {
//                JOptionPane.showMessageDialog(this, "Bạn đang đăng nhập với quyền Nhân viên.");
//            }
//
//            // Hiển thị giao diện chính và đóng giao diện đăng nhập
//            mn.setVisible(true);
//            this.dispose();
//        } else {
//            // Thông báo nếu thông tin đăng nhập không đúng
//            JOptionPane.showMessageDialog(this, "Tên tài khoản hoặc mật khẩu không đúng. Vui lòng thử lại!");
//        }
    }//GEN-LAST:event_btnsubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jlbMsg;
    private javax.swing.JPanel jpnroot;
    private javax.swing.JPasswordField passmatkhau;
    private javax.swing.JTextField txttendangnhap;
    // End of variables declaration//GEN-END:variables
}
