/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import com.toedter.calendar.JDateChooser;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import model.KhachHang;
import model.NhanVien;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import service.NhanVienSevicer;

/**
 *
 * @author trinh thanh
 */
public class QuanLyNhanVien extends javax.swing.JPanel {

    ArrayList<NhanVien> arr = new ArrayList<>();
    DefaultTableModel model = new DefaultTableModel();
    NhanVienSevicer sevicer = new NhanVienSevicer();

    /**
     * Creates new form QuanLyNhanVien
     */
    public QuanLyNhanVien() {
        initComponents();
        model = (DefaultTableModel) tblnhanvien.getModel();
        arr = sevicer.getAll();
        viewdata(arr);

    }

    public void viewdata(List<NhanVien> nhanVienList) {
        model.setRowCount(0);
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        for (NhanVien nv : nhanVienList) {
            Object[] row = new Object[]{
                nv.getMaNhanVien(), nv.getTenTaiKhoan(), nv.getMatKhau(),
                nv.getQuyen(), nv.getTen(), nv.isGioiTinh() ? "Nam" : "Nữ",
                nv.getDiaChi(), nv.getSđt(),
                nv.isTrangThai() ? "Đang Làm" : "Nghỉ Làm"
            };
            model.addRow(row);
        }
    }

    public void initdata(int index) {
        NhanVien nv = arr.get(index);
        txtmanhanvien.setText(nv.getMaNhanVien());
        txttennhanvien.setText(nv.getTen());
        rdonam.setSelected(nv.isGioiTinh());
        rdonu.setSelected(!nv.isGioiTinh());
        txtdiachi.setText(nv.getDiaChi());
        txtsodienthoai.setText(nv.getSđt());
        txttaikhoan.setText(nv.getTenTaiKhoan());
        txtmatkhau.setText(nv.getMatKhau());
        cboquyen.setSelectedItem(nv.getQuyen());
        rdodanglam.setSelected(nv.isTrangThai());
        rdonghilam.setSelected(!nv.isTrangThai());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtmanhanvien = new javax.swing.JTextField();
        txttennhanvien = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rdonam = new javax.swing.JRadioButton();
        rdonu = new javax.swing.JRadioButton();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        txtdiachi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rdodanglam = new javax.swing.JRadioButton();
        rdonghilam = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblnhanvien = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txttaikhoan = new javax.swing.JTextField();
        nhapExcel = new javax.swing.JButton();
        cboquyen = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtsodienthoai = new javax.swing.JTextField();
        txtmatkhau = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnLamMoi = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1006, 767));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("QUẢN LÝ NHÂN VIÊN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Mã Nhân Viên:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Họ Tên:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Quyền");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("GIỚI TÍNH:");

        buttonGroup1.add(rdonam);
        rdonam.setText("Nam");

        buttonGroup1.add(rdonu);
        rdonu.setText("Nữ");

        btnthem.setBackground(new java.awt.Color(0, 51, 255));
        btnthem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnthem.setForeground(new java.awt.Color(255, 255, 255));
        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setBackground(new java.awt.Color(0, 255, 51));
        btnsua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsua.setForeground(new java.awt.Color(255, 255, 255));
        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(51, 255, 204));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Xuất EXCEL");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Địa Chỉ:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Trạng Thái:");

        buttonGroup2.add(rdodanglam);
        rdodanglam.setText("Đang Làm");
        rdodanglam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdodanglamActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdonghilam);
        rdonghilam.setText("Nghỉ Làm");

        tblnhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Tài Khoản", "Mật Khẩu", "Quyền", "Họ Tên", "Giới Tính", "Địa Chỉ", "Số Điện Thoại", "Trạng Thái"
            }
        ));
        tblnhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblnhanvienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblnhanvien);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Tài Khoản:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Mật Khẩu:");

        nhapExcel.setBackground(new java.awt.Color(0, 204, 51));
        nhapExcel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nhapExcel.setForeground(new java.awt.Color(255, 255, 255));
        nhapExcel.setText("Nhập");
        nhapExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapExcelActionPerformed(evt);
            }
        });

        cboquyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Nhân Viên" }));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Số Điện Thoại:");

        jLabel6.setText("Tìm Kiếm:");

        jTextField1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField1CaretUpdate(evt);
            }
        });

        btnLamMoi.setBackground(new java.awt.Color(0, 255, 51));
        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel4))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttennhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(12, 12, 12)
                                .addComponent(txtmanhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel6)))))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnthem)
                        .addGap(46, 46, 46)
                        .addComponent(btnsua)
                        .addGap(40, 40, 40)
                        .addComponent(btnLamMoi)
                        .addGap(44, 44, 44)
                        .addComponent(nhapExcel)
                        .addGap(42, 42, 42)
                        .addComponent(jButton6))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(13, 13, 13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txttaikhoan)
                            .addComponent(cboquyen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(32, 32, 32)
                                .addComponent(rdonam)
                                .addGap(44, 44, 44)
                                .addComponent(rdonu))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(txtsodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(rdodanglam)
                                .addGap(20, 20, 20)
                                .addComponent(rdonghilam)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(txtsodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmanhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel3)
                                                .addComponent(txttaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(rdonam)
                                                .addComponent(jLabel10))
                                            .addComponent(rdonu))
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(txttennhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12)
                                            .addComponent(rdodanglam)
                                            .addComponent(rdonghilam)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel4)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboquyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jLabel6)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnthem)
                    .addComponent(btnsua)
                    .addComponent(nhapExcel)
                    .addComponent(btnLamMoi))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rdodanglamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdodanglamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdodanglamActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        if (txtmanhanvien.getText().isEmpty() || txttennhanvien.getText().isEmpty()
                || txtdiachi.getText().isEmpty() || txtsodienthoai.getText().isEmpty()
                || txttaikhoan.getText().isEmpty() || txtmatkhau.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Nhập Dữ Liệu!");
            return;
        }

        String maNV = txtmanhanvien.getText();
        for (NhanVien nv : arr) {
            if (nv.getMaNhanVien().equals(maNV)) {
                JOptionPane.showMessageDialog(this, "Mã Này Đã Tồn Tại!");
                return;
            }
        }

        NhanVien nv = new NhanVien();
        nv.setMaNhanVien(maNV);
        nv.setTen(txttennhanvien.getText());
        nv.setGioiTinh(rdonam.isSelected());
        nv.setDiaChi(txtdiachi.getText());
        nv.setSđt(txtsodienthoai.getText());
        nv.setTenTaiKhoan(txttaikhoan.getText());
        nv.setMatKhau(txtmatkhau.getText());
        nv.setQuyen((String) cboquyen.getSelectedItem());
        nv.setTrangThai(rdodanglam.isSelected());

        arr.add(nv);
        sevicer.addNhanVien(nv);
        viewdata(arr);
        JOptionPane.showMessageDialog(this, "Thêm Thành Công!");
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        int index = tblnhanvien.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Chưa Chọn Dòng Để Cập Nhật!");
            return;
        }
        

        NhanVien nv = arr.get(index);
        nv.setMaNhanVien(txtmanhanvien.getText());
        nv.setTen(txttennhanvien.getText());
        nv.setGioiTinh(rdonam.isSelected());
        nv.setDiaChi(txtdiachi.getText());
        nv.setSđt(txtsodienthoai.getText());
        nv.setTenTaiKhoan(txttaikhoan.getText());
        nv.setMatKhau(txtmatkhau.getText());
        nv.setQuyen((String) cboquyen.getSelectedItem());
        nv.setTrangThai(rdodanglam.isSelected());

        sevicer.updateNhanVien(nv);
        viewdata(arr);
        JOptionPane.showMessageDialog(this, "Cập Nhật Thành Công!");

    }//GEN-LAST:event_btnsuaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Lưu file Excel");
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Excel Files", "xlsx"));

        // Hiện hộp thoại lưu file
        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();

            // Kiểm tra xem file có đuôi .xlsx không
            if (!fileToSave.getAbsolutePath().endsWith(".xlsx")) {
                fileToSave = new File(fileToSave.getAbsolutePath() + ".xlsx");
            }

            try (Workbook workbook = new XSSFWorkbook()) {
                Sheet sheet = workbook.createSheet("Nhân Viên");
                Row headerRow = sheet.createRow(0);

                // Tạo tiêu đề cột
                headerRow.createCell(1).setCellValue("Mã Nhân Viên");
                headerRow.createCell(2).setCellValue("Họ Tên");
                headerRow.createCell(3).setCellValue("Giới Tính");
                headerRow.createCell(4).setCellValue("Địa Chỉ");
                headerRow.createCell(5).setCellValue("Số Điện Thoại");
                headerRow.createCell(6).setCellValue("Ngày Vào Làm");
                headerRow.createCell(7).setCellValue("Trạng Thái");

                // Xuất dữ liệu từ JTable ra file Excel
                for (int i = 0; i < model.getRowCount(); i++) {
                    Row row = sheet.createRow(i + 1);
                    for (int j = 0; j < model.getColumnCount(); j++) {
                        Object cellValue = model.getValueAt(i, j);
                        row.createCell(j).setCellValue(cellValue != null ? cellValue.toString() : "");
                    }
                }

                // Lưu file Excel
                try (FileOutputStream outputStream = new FileOutputStream(fileToSave)) {
                    workbook.write(outputStream);
                    JOptionPane.showMessageDialog(this, "Xuất Excel thành công!");
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi khi xuất Excel: " + e.getMessage());
            }
        }


    }//GEN-LAST:event_jButton6ActionPerformed

    private void nhapExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapExcelActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser("H:\\");
        fileChooser.setDialogTitle("Chọn file Excel để nhập dữ liệu");
        fileChooser.setFileFilter(new FileNameExtensionFilter("Excel Files", "xlsx"));

        int userSelection = fileChooser.showOpenDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToOpen = fileChooser.getSelectedFile();
            try (FileInputStream fis = new FileInputStream(fileToOpen); Workbook workbook = WorkbookFactory.create(fis)) {

                Sheet sheet = workbook.getSheetAt(0);
                model.setRowCount(0); // Xóa dữ liệu hiện tại trong bảng

                for (Row row : sheet) {
                    if (row.getRowNum() == 0) {
                        continue; // Bỏ qua hàng tiêu đề
                    }
                    String maNhanVien = row.getCell(0).getStringCellValue();
                    String hoTen = row.getCell(1).getStringCellValue();
                    String gioiTinh = row.getCell(2).getStringCellValue();
                    String diaChi = row.getCell(3).getStringCellValue();
                    String soDienThoai = row.getCell(4).getStringCellValue();
                    String ngayVaoLam = row.getCell(5).getStringCellValue();
                    String trangThai = row.getCell(6).getStringCellValue();

                    // Kiểm tra xem các trường dữ liệu có hợp lệ không
                    if (maNhanVien.isEmpty() || hoTen.isEmpty() || gioiTinh.isEmpty() || diaChi.isEmpty() || soDienThoai.isEmpty() || ngayVaoLam.isEmpty() || trangThai.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Dữ liệu không hợp lệ trong hàng: " + (row.getRowNum() + 1));
                        continue;
                    }

                    // Thêm dữ liệu vào bảng
                    model.addRow(new Object[]{maNhanVien, hoTen, gioiTinh, diaChi, soDienThoai, ngayVaoLam, trangThai});
                }
                JOptionPane.showMessageDialog(this, "Nhập dữ liệu thành công từ file: " + fileToOpen.getName());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi khi nhập Excel: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_nhapExcelActionPerformed

    private void tblnhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblnhanvienMouseClicked
        // TODO add your handling code here:
        int index = tblnhanvien.getSelectedRow();
        this.initdata(index);
        txtmanhanvien.setEditable(false);
    }//GEN-LAST:event_tblnhanvienMouseClicked

    private void jTextField1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField1CaretUpdate
        // TODO add your handling code here:
        String keyword = jTextField1.getText();
        List<NhanVien> nhanVienList = sevicer.searchNhanVien(keyword);
        viewdata(nhanVienList);
        
    }//GEN-LAST:event_jTextField1CaretUpdate

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
      txtmanhanvien.setText("");
       txtmanhanvien.setEditable(true);
       txtdiachi.setText("");
       txtmatkhau.setText("");
       txttennhanvien.setText("");
       txttaikhoan.setText("");
       txtsodienthoai.setText("");
    }//GEN-LAST:event_btnLamMoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cboquyen;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton nhapExcel;
    private javax.swing.JRadioButton rdodanglam;
    private javax.swing.JRadioButton rdonam;
    private javax.swing.JRadioButton rdonghilam;
    private javax.swing.JRadioButton rdonu;
    private javax.swing.JTable tblnhanvien;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtmanhanvien;
    private javax.swing.JPasswordField txtmatkhau;
    private javax.swing.JTextField txtsodienthoai;
    private javax.swing.JTextField txttaikhoan;
    private javax.swing.JTextField txttennhanvien;
    // End of variables declaration//GEN-END:variables
}
