/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JPanel;
import model.ChuyenManHinh;
import model.DanhMucBean;
import model.NhanVien;

/**
 *
 * @author trinh thanh
 */
public class QuanThanhCon extends JPanel {


    /**
     * Creates new form QuanThanhCon
     */
    public QuanThanhCon( ) {
        initComponents();

        List<DanhMucBean> arr = new ArrayList<>();
        arr.add(new DanhMucBean("QuanLySachh", jpnquanlysach, jlbquanlysach));
        arr.add(new DanhMucBean("QuanLyNhaXuatBan", jpnnxb, jlbnxb));
        arr.add(new DanhMucBean("QuanLyTheLoai", jpntheloai, jlbtheloai));
        arr.add(new DanhMucBean("QuanLyTacGia", jpntacgia, jlbtacgia));
        ChuyenManHinh chuyenManHinh = new ChuyenManHinh(jpnview);
        chuyenManHinh.setView1(jpnquanlysach, jlbquanlysach);
        chuyenManHinh.setEvent(arr);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpnnxb = new javax.swing.JPanel();
        jlbnxb = new javax.swing.JLabel();
        jpntheloai = new javax.swing.JPanel();
        jlbtheloai = new javax.swing.JLabel();
        jpnquanlysach = new javax.swing.JPanel();
        jlbquanlysach = new javax.swing.JLabel();
        jpntacgia = new javax.swing.JPanel();
        jlbtacgia = new javax.swing.JLabel();
        jpnview = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1049, 646));

        jPanel1.setBackground(new java.awt.Color(102, 102, 153));

        jlbnxb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbnxb.setForeground(new java.awt.Color(255, 255, 255));
        jlbnxb.setText("Nhà Xuất Bản");

        javax.swing.GroupLayout jpnnxbLayout = new javax.swing.GroupLayout(jpnnxb);
        jpnnxb.setLayout(jpnnxbLayout);
        jpnnxbLayout.setHorizontalGroup(
            jpnnxbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnnxbLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jlbnxb)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jpnnxbLayout.setVerticalGroup(
            jpnnxbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbnxb, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jlbtheloai.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbtheloai.setForeground(new java.awt.Color(255, 255, 255));
        jlbtheloai.setText("Thể Loại");

        javax.swing.GroupLayout jpntheloaiLayout = new javax.swing.GroupLayout(jpntheloai);
        jpntheloai.setLayout(jpntheloaiLayout);
        jpntheloaiLayout.setHorizontalGroup(
            jpntheloaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpntheloaiLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jlbtheloai)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jpntheloaiLayout.setVerticalGroup(
            jpntheloaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbtheloai, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        jlbquanlysach.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbquanlysach.setForeground(new java.awt.Color(255, 255, 255));
        jlbquanlysach.setText("Quản Lý Sách");

        javax.swing.GroupLayout jpnquanlysachLayout = new javax.swing.GroupLayout(jpnquanlysach);
        jpnquanlysach.setLayout(jpnquanlysachLayout);
        jpnquanlysachLayout.setHorizontalGroup(
            jpnquanlysachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnquanlysachLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jlbquanlysach)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jpnquanlysachLayout.setVerticalGroup(
            jpnquanlysachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbquanlysach, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jlbtacgia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbtacgia.setForeground(new java.awt.Color(255, 255, 255));
        jlbtacgia.setText("Tác Giả");

        javax.swing.GroupLayout jpntacgiaLayout = new javax.swing.GroupLayout(jpntacgia);
        jpntacgia.setLayout(jpntacgiaLayout);
        jpntacgiaLayout.setHorizontalGroup(
            jpntacgiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpntacgiaLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jlbtacgia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpntacgiaLayout.setVerticalGroup(
            jpntacgiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbtacgia, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnquanlysach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpnnxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpntheloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jpntacgia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jpnquanlysach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jpnnxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jpntheloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jpntacgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnviewLayout = new javax.swing.GroupLayout(jpnview);
        jpnview.setLayout(jpnviewLayout);
        jpnviewLayout.setHorizontalGroup(
            jpnviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
        );
        jpnviewLayout.setVerticalGroup(
            jpnviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbnxb;
    private javax.swing.JLabel jlbquanlysach;
    private javax.swing.JLabel jlbtacgia;
    private javax.swing.JLabel jlbtheloai;
    private javax.swing.JPanel jpnnxb;
    private javax.swing.JPanel jpnquanlysach;
    private javax.swing.JPanel jpntacgia;
    private javax.swing.JPanel jpntheloai;
    private javax.swing.JPanel jpnview;
    // End of variables declaration//GEN-END:variables

}
